language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  
before_script:
  # Set up Composer
  - composer self-update || true
  - composer install --prefer-dist

script:
  # PHPUnit
  - php vendor/bin/phpunit --colors --coverage-text
